version: '3'

services:
  web:
    build: ./docker
    ports:
    - ${ANNIVERSARY_APACHE_PORT}:80
    command: sh /init.sh
    volumes:
    - ${ANNIVERSARY_SRC}:/var/www/html/laravel-init-docker
    - ./docker/web:/etc/apache2/sites-enabled
    - ./docker/web/init.sh:/init.sh
    - ./logs/web:/var/log/apache2

  db:
    image: mysql:5.7
    ports:
    - ${MYSQL_HOST_PORT}:3306
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  selenium-hub:
      image: selenium/hub:3.141.59-copernicium
      container_name: selenium-hub
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.141.59-copernicium
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  adminer:
    image: adminer
    ports:
    - 1234:8080
    environment:
    - ADMINER_DEFAULT_SERVER=db
