version: '3'

services:
  web:
    build: ./docker
    ports:
    - ${ANNIVERSARY_APACHE_PORT}:80
    command: sh /init.sh
    volumes:
    - ${ANNIVERSARY_SRC}:/var/www/html/laravel-init-docker
    - ./docker/web:/etc/apache2/sites-enabled
    - ./docker/web/init.sh:/init.sh
    - ./logs/web:/var/log/apache2

  db:
    image: mysql:5.7
    ports:
    - ${MYSQL_HOST_PORT}:3306
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}


  adminer:
    image: adminer
    ports:
    - 4567:8080
    environment:
    - ADMINER_DEFAULT_SERVER=db